sudo: false
language: rust
script: cargo test --all
matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly
    include:
        - rust: stable
        - rust: beta
        - rust: nightly

        - rust: stable
          script: cargo test --all --features macro

