sudo: false
language: rust
matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly
    include:
        - rust: stable
        - rust: beta
        - rust: nightly
        - rust: 1.31.0

        - rust: stable
          script: cargo test --features macro

