[package]

name = "mime"
version = "0.0.4"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
license = "MIT"
description = "Strongly Typed Mimes"
documentation = "http://hyperium.github.io/mime.rs"
repository = "https://github.com/hyperium/mime.rs"

[dependencies]
log = "*"
